### ISSUE TITLE
grid_seq in help page for mouthwash_second_step

### ISSUE THREAD

**Issue by stephens999** [dcgerard/vicar#4]
the help says that lambda_seq is "A numeric vector with elements all greater than or equal to 1. These are the tuning parameters for the mixing proportions. This can only be specified if grid_seq is also specified."

but grid_seq is not a parameter here.

**Comment by dcgerard** [comment]
Thanks! I think `tau2_seq` used to be called `grid_seq` before I added the uniform option. I think `lambda_seq` has to be specified now. Will fix!
