### ISSUE TITLE
mouthwash_second_step does not run with normal likelihood

### ISSUE THREAD

**Issue by stephens999** [dcgerard/vicar#5]
when I run:

set.seed(1)
n=1000
bhat = rt(n,df=4) # t with 4 df
shat = rep(1,n)
library(ashr)
bhat.ash.t4 = ash(bhat,shat,df = 4)
bhat.ash.norm = ash(bhat,shat)
get_pi0(bhat.ash.norm)
get_pi0(bhat.ash.t4)
min(get_lfsr(bhat.ash.norm))
min(get_lfsr(bhat.ash.t4))

library("vicar")
a = matrix(rep(1,n),nrow = n, ncol=1) # just put in an "intercept" confounder with no effect
a_seq = bhat.ash.norm$fitted_g$a
b_seq = bhat.ash.norm$fitted_g$b
lambda_seq = rep(1,length(a_seq))
lambda_seq[1] = 10
bhat.m.norm = mouthwash_second_step(bhat,shat,a,lambda_seq = lambda_seq,a_seq = a_seq, b_seq=b_seq,mixing_dist = "uniform", likelihood="normal", scale_var = TRUE)

I get an error: 

Error in stats::pt(-Y[which_switch], df = degrees_freedom) : argument "degrees_freedom" is missing, with no default

**Comment by dcgerard** [comment]
Thanks! Internally, I think I run this with `degrees_freedom = Inf`. Will fix this for `mouthwash_second_step`!
