### ISSUE TITLE
ERROR: dependencies ‘limma’, ‘sva’, ‘cate’ are not available for package ‘vicar’

### ISSUE THREAD

**Issue by youngseok-kim** [dcgerard/vicar#7]
In the installation instructions please add the code to install the limma, sva and cate packages from Bioconductor.

(Posted by Youngseok & Peter.)

Notifying @pcarbo.

**Comment by dcgerard** [comment]
`cate` is actually a CRAN package [see here](https://cran.r-project.org/web/packages/cate/index.html), so I think it should install automatically if you use `devtools::install_github`.

**Comment by pcarbo** [comment]
@dcgerard For some reason `install_github` doesn't install the `cate` dependency automatically so I adjusted the installation instructions.
